name: "Deploying a CI/CD for .NET sample app using GitHub Actions"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore Packages
      run: nuget restore HelloWorldSampleApp.sln

    - name: Build solution
      run: msbuild HelloWorldSampleApp.sln /p:Configuration=Release /p:DeployOnBuild=true

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Uploading the application artifacts to Amazon S3
      shell: cmd
      run: C:\"Program Files"\Amazon\AWSCLIV2\aws s3 cp "D:\a\HelloWorldSampleApp\HelloWorldSampleApp\HelloWorldSampleApp\obj\Release\Package\HelloWorldSampleApp.zip" s3://dotnet-cicd-bucket/
      
    - name: Download the zip file from S3
      shell: cmd
      run: C:\"Program Files"\Amazon\AWSCLIV2\aws s3 cp s3://dotnet-cicd-bucket/HelloWorldSampleApp.zip .
      
    - name: Unzipping the Zip file
      shell: powershell
      run: |
        Expand-Archive -Path .\HelloWorldSampleApp.zip -DestinationPath .
        ls HelloWorldSampleApp\obj\Release\Package\PackageTmp

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.232.147.60 >> ~/.ssh/known_hosts
        
    - name: Copy File to EC2
      run: scp -i ~/.ssh/id_rsa /path/to/local/file ec2-user@13.232.147.60:/C:/inetpub/wwwroot/
        
    # - name: Copy Build Folder
    #   run: scp -r HelloWorldSampleApp\obj\Release\Package\PackageTmp\* ip-172-31-2-206.ap-south-1.compute.internal:/C:/inetpub/wwwroot
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Deploy to IIS Server
    #   shell: powershell
    #   run: |
    #     Start-Process powershell -ArgumentList "iisreset /stop" -Verb RunAs
    #     Copy-Item ./publish/* C:/inetpub/wwwroot/ -Recurse -Force
    #     Start-Process powershell -ArgumentList "iisreset /start" -Verb RunAs

